"""vote with session id

Revision ID: 133df0ba7a1d
Revises: 
Create Date: 2025-11-04 01:31:57.615072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133df0ba7a1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('session_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_ballots_session_id'), 'ballots', ['session_id'], unique=False)
    op.create_unique_constraint('uq_ballot_user_session', 'ballots', ['user_id', 'session_id'])
    op.drop_column('ballots', 'context_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('context_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_ballot_user_session', 'ballots', type_='unique')
    op.drop_index(op.f('ix_ballots_session_id'), table_name='ballots')
    op.drop_column('ballots', 'session_id')
    # ### end Alembic commands ###
