"""initial migration

Revision ID: 7e001f66c289
Revises: 
Create Date: 2025-10-21 16:52:56.959808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e001f66c289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('weather', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('weather', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('weather', 'temperature',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.drop_index(op.f('ix_weather_city'), table_name='weather')
    op.create_index(op.f('ix_weather_city'), 'weather', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_city'), table_name='weather')
    op.create_index(op.f('ix_weather_city'), 'weather', ['city'], unique=True)
    op.alter_column('weather', 'temperature',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('weather', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('weather', 'created_at')
    op.drop_column('weather', 'description')
    # ### end Alembic commands ###
