"""add session_id to activity

Revision ID: 93e9a09c0d19
Revises: 
Create Date: 2025-11-04 02:16:50.603205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e9a09c0d19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_activity_session_id'), 'activity', ['session_id'], unique=False)
    op.drop_index(op.f('ix_ballots_user_id'), table_name='ballots')
    op.drop_constraint(op.f('uq_ballot_user_session'), 'ballots', type_='unique')
    op.create_unique_constraint('uq_user_session', 'ballots', ['user_id', 'session_id'])
    op.drop_index(op.f('ix_preference_ranks_activity_id'), table_name='preference_ranks')
    op.drop_index(op.f('ix_preference_ranks_ballot_id'), table_name='preference_ranks')
    op.drop_constraint(op.f('uq_rank_ballot_activity'), 'preference_ranks', type_='unique')
    op.drop_constraint(op.f('uq_rank_ballot_rank'), 'preference_ranks', type_='unique')
    op.create_unique_constraint('uq_ballot_activity', 'preference_ranks', ['ballot_id', 'activity_id'])
    op.create_unique_constraint('uq_ballot_rank', 'preference_ranks', ['ballot_id', 'rank'])
    op.execute("UPDATE activity SET session_id = 'default_session' WHERE session_id IS NULL")
    op.alter_column('activity', 'session_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ballot_rank', 'preference_ranks', type_='unique')
    op.drop_constraint('uq_ballot_activity', 'preference_ranks', type_='unique')
    op.create_unique_constraint(op.f('uq_rank_ballot_rank'), 'preference_ranks', ['ballot_id', 'rank'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_rank_ballot_activity'), 'preference_ranks', ['ballot_id', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_preference_ranks_ballot_id'), 'preference_ranks', ['ballot_id'], unique=False)
    op.create_index(op.f('ix_preference_ranks_activity_id'), 'preference_ranks', ['activity_id'], unique=False)
    op.drop_constraint('uq_user_session', 'ballots', type_='unique')
    op.create_unique_constraint(op.f('uq_ballot_user_session'), 'ballots', ['user_id', 'session_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ballots_user_id'), 'ballots', ['user_id'], unique=False)
    op.drop_index(op.f('ix_activity_session_id'), table_name='activity')
    op.drop_column('activity', 'session_id')
    # ### end Alembic commands ###
